/**
 * Public API surface of the host half.
 *
 * plan-05: the historical single-module import face (`import { … } from
 * "dsh-plugin-goldboard"`) preserved as one re-export facade over the split
 * modules. The composition root (lib/index.js) does `export * from` here, so
 * existing consumers — including the unit suites — keep working while the
 * implementation lives in focused files.
 */

export {
  CALCULATION_VERSION,
  INDICATOR_METHODS,
  assessMarketQuality,
  closedBars,
  isBarClosed,
  minimumCoverageForWindow,
  normalizeBarRecord,
  normalizeQuoteRecord,
} from "./market-quality.js";
export {
  DEFAULT_CONFIG,
  SETTINGS_NAMESPACE,
  SETTINGS_SCHEMA,
  mergeConfigPatch,
  mergeConfigSection,
  mergeSecrets,
  normalizeConfig,
  redactConfig,
  sectionForSettingsStore,
} from "./config.js";
export {
  MIDNIGHT_WINDOW_END_MINUTES,
  PLAN_WINDOWS,
  SESSION_WARMUP_MS,
  alignStart,
  beijingDateForNow,
  beijingParts,
  buildSessionCalendar,
  computeMarketState,
  computeNextMarketOpen,
  coverageGate,
  filterBarsToTradingHours,
  isOpenMinute,
  windowCoverage,
  COVERAGE_REANCHOR_GAP_MINUTES,
} from "./market-time.js";
export {
  INDICATOR_WARMUP_BARS,
  atr,
  bollinger,
  computeIndicatorSet,
  emaSeries,
  macd,
  resampleBars,
  rsi,
  sma,
} from "./indicators.js";
export * from "./shared.js";
export {
  DATA_SOURCES,
  FETCH_TIMEOUT_MS,
  QUOTE_TIMEOUT_MS,
  STALE_QUOTE_MS,
  SourceRegistry,
  __setFetchImpl,
  __setQuoteChainTiming,
  fetchCmbQuote,
  fetchDomesticQuote,
  fetchEastmoneyBars,
  fetchGoldApiQuote,
  fetchGoldPriceTodayQuote,
  fetchJdGoldQuote,
  fetchJijinhaoQuote,
  fetchSgeDailyBars,
  fetchSgeQuote,
  fetchSixtySecondsQuote,
  fetchYahooXauDailyBars,
  fetchYahooXauQuote,
  getDefaultSourceRegistry,
  isCircuitOpen,
  isDomesticQuoteFresh,
  markSourceFailure,
  markSourceSuccess,
  parseCmbMarketCenterQuote,
  parseEastmoneyDomesticQuote,
  parseEastmoneyKlines,
  parseGoldApiQuote,
  parseGoldPriceTodayQuote,
  parseJdGoldQuote,
  parseJijinhaoQuote,
  parseQuoteTimestamp,
  parseSgeDailyBars,
  parseSgeQuote,
  parseSinaDomesticQuote,
  parseSixtySecondsGoldPrice,
  parseTencentForexQuote,
  parseTencentXauQuote,
  parseYahooFinanceKlines,
  parseYahooFinanceQuote,
} from "./sources.js";
export {
  BARS_SEED_VERSION,
  BAR_INTERVALS,
  MAX_BARS,
  aggregateSubBars,
  applyManualCmbMinuteBars,
  ensureBars,
  hasMissingLeadingBars,
  hasMissingRecentBars,
  listMissingCmbMinuteSlots,
  mergeKlines,
  migrateBarsSeedVersion,
  parseManualCmbMinuteEntries,
  recordTick,
  seedBars,
} from "./bars.js";
export {
  computePlan,
  CONFIDENCE_MAX,
  LANE_RECOVER_TICKS,
  LANE_SWITCH_TICKS,
  PREMIUM_DAY_SAMPLE_CAP,
  PREMIUM_HISTORY_CAP,
  PREMIUM_MIN_DAYS,
  SIGNAL_LANES,
  TROY_OUNCE_GRAMS,
  applySignalPolicy,
  assessSpreadPremium,
  cleanCmbSpreadSamples,
  defaultSignalState,
  dynamicCmbSpread,
  hasCmbFallback,
  isBearishWeaknessBar,
  laneAvailability,
  resolveSignalLane,
  stageReduceGrams,
  suggestedGrams,
  updatePremiumHistory,
} from "./plan.js";
export {
  ALERT_LOG_CAP,
  ACTION_LABELS_EN,
  ACTION_LABELS_ZH,
  ORDER_UPDATE_ESCALATION_DELTA_PER_GRAM,
  ORDER_UPDATE_MIN_DELTA_PER_GRAM,
  ORDER_UPDATE_MIN_INTERVAL_MS,
  SELL_ACTIONS,
  buildAlertMessage,
  buildLaneSwitchMessage,
  buildOrderChangeMessage,
  buildOrderDriftNote,
  buildSpreadAlertMessage,
  classifyOrderTransition,
  dispatchAlert,
  mergeTestConfig,
  renderWebhookTemplate,
  runAlertEvaluation,
  sameSuggestedOrder,
  systemNotify,
} from "./alerts.js";
export {
  SNAPSHOT_REBUILD_MIN_MS,
  TREND_POINTS,
  barsView,
  buildSnapshot,
  replayMarketPlan,
  snapshotCacheStale,
} from "./snapshot.js";
export { MAX_CONFIG_BYTES, route } from "./routes.js";
export {
  ApiLogStore,
  StatePersister,
  dshHome,
  makeWriteQueue,
  pluginDir,
  readApiLogsFromFile,
  readJson,
  restoreRuntimeState,
  rotateApiLogIfNeeded,
  writeJsonAtomic,
} from "./store.js";
